# Generated by Django 4.1.5 on 2023-01-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Task'),
        ),
    ]
