# Generated by Django 4.1.5 on 2023-01-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_task_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Считчик', 'verbose_name_plural': 'Счетчики'},
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.DecimalField(decimal_places=2, max_digits=500000000, verbose_name='Task'),
        ),
    ]
