# Generated by Django 4.1.5 on 2023-01-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_task_options_alter_task_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.DecimalField(decimal_places=0, max_digits=500000, verbose_name=''),
        ),
    ]
