# Generated by Django 4.1.5 on 2023-02-01 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_task_comments_telefon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text_comment',
            new_name='text_comments',
        ),
    ]
