# Generated by Django 4.1.5 on 2023-02-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_text_comment_comments_text_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text_comments',
            new_name='text_comment',
        ),
    ]
