# Generated by Django 4.1.5 on 2023-02-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Гости сайта', 'verbose_name_plural': 'Гости сайта'},
        ),
        migrations.AddField(
            model_name='visit',
            name='name',
            field=models.CharField(default='name', max_length=100, verbose_name='Количество посетителей сайта: '),
            preserve_default=False,
        ),
    ]
