# Generated by Django 4.1.5 on 2023-02-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_visit_options_visit_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Гость сайта', 'verbose_name_plural': 'Гости сайта'},
        ),
    ]
