# Generated by Django 4.1.5 on 2023-02-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_visit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={},
        ),
        migrations.RemoveField(
            model_name='visit',
            name='count',
        ),
        migrations.AlterField(
            model_name='visit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Количество гостей:'),
        ),
    ]
