# Generated by Django 4.1.5 on 2023-02-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_visit_options_remove_visit_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Гости сайта', 'verbose_name_plural': 'Гости сайта'},
        ),
        migrations.RemoveField(
            model_name='visit',
            name='name',
        ),
        migrations.AddField(
            model_name='visit',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
