# Generated by Django 4.1.5 on 2023-02-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_visit_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Гости сайта', 'verbose_name_plural': 'Ip Address:'},
        ),
    ]
