# Generated by Django 4.1.5 on 2023-02-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_visit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Количество'),
        ),
    ]
