# Generated by Django 4.1.5 on 2023-02-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_visit_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Ip', 'verbose_name_plural': 'Гости сайта'},
        ),
        migrations.RemoveField(
            model_name='visit',
            name='name',
        ),
        migrations.AddField(
            model_name='visit',
            name='ip',
            field=models.CharField(default=None, max_length=100, verbose_name='Ip Address'),
            preserve_default=False,
        ),
    ]
