# Generated by Django 4.1.5 on 2023-02-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_visit_options_remove_visit_name_visit_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='ip',
            field=models.CharField(max_length=50, verbose_name='Ip Address'),
        ),
    ]
