# Generated by Django 4.1.5 on 2023-02-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_visit_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='ip',
            new_name='ip_addr',
        ),
    ]
