# Generated by Django 4.1.5 on 2023-02-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_rename_ip_visit_ip_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='ip_addr',
            field=models.CharField(max_length=50, verbose_name='Ip'),
        ),
    ]
