# Generated by Django 4.1.5 on 2023-02-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_visit_options_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='data',
            field=models.CharField(default='0000', max_length=50, verbose_name='Data'),
            preserve_default=False,
        ),
    ]
