# Generated by Django 4.1.5 on 2023-02-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_visit_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='data',
            field=models.CharField(max_length=17, verbose_name='Data'),
        ),
    ]
